/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ProjekterRouteImport } from './routes/projekter'
import { Route as ProblemerRouteImport } from './routes/problemer'
import { Route as PriserRouteImport } from './routes/priser'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as OrdbogRouteImport } from './routes/ordbog'
import { Route as OmRouteImport } from './routes/om'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as IndsigterRouteImport } from './routes/indsigter'
import { Route as EnRouteImport } from './routes/en'
import { Route as DatakilderRouteImport } from './routes/datakilder'
import { Route as DataRouteImport } from './routes/data'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BrancherRouteImport } from './routes/brancher'
import { Route as BookDemoRouteImport } from './routes/book-demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as UseCasesSlugRouteImport } from './routes/use-cases.$slug'
import { Route as ProblemerSlugRouteImport } from './routes/problemer.$slug'
import { Route as PlatformSmartconnectRouteImport } from './routes/platform.smartconnect'
import { Route as PlatformImpactExchangeRouteImport } from './routes/platform.impact-exchange'
import { Route as PlatformEsgLedgerRouteImport } from './routes/platform.esg-ledger'
import { Route as PlatformDecisionsiqRouteImport } from './routes/platform.decisionsiq'
import { Route as OrdbogTermRouteImport } from './routes/ordbog.$term'
import { Route as LoesningerNaturprojekterRouteImport } from './routes/loesninger.naturprojekter'
import { Route as LoesningerKommunerRouteImport } from './routes/loesninger.kommuner'
import { Route as LoesningerIndustriRouteImport } from './routes/loesninger.industri'
import { Route as LoesningerEsgComplianceRouteImport } from './routes/loesninger.esg-compliance'
import { Route as IndsigterSlugRouteImport } from './routes/indsigter.$slug'
import { Route as EnPricingRouteImport } from './routes/en.pricing'
import { Route as EnPlatformRouteImport } from './routes/en.platform'
import { Route as EnDashboardRouteImport } from './routes/en.dashboard'
import { Route as EnContactRouteImport } from './routes/en.contact'
import { Route as EnBookDemoRouteImport } from './routes/en.book-demo'
import { Route as EnAboutRouteImport } from './routes/en.about'
import { Route as DataSlugRouteImport } from './routes/data.$slug'
import { Route as BrancherSlugRouteImport } from './routes/brancher.$slug'
import { Route as ApiAiEsgAnalyseRouteImport } from './routes/api/ai-esg-analyse'
import { Route as EnPlatformSmartconnectRouteImport } from './routes/en.platform.smartconnect'
import { Route as EnPlatformImpactExchangeRouteImport } from './routes/en.platform.impact-exchange'
import { Route as EnPlatformEsgLedgerRouteImport } from './routes/en.platform.esg-ledger'
import { Route as EnPlatformDecisionsiqRouteImport } from './routes/en.platform.decisionsiq'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjekterRoute = ProjekterRouteImport.update({
  id: '/projekter',
  path: '/projekter',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemerRoute = ProblemerRouteImport.update({
  id: '/problemer',
  path: '/problemer',
  getParentRoute: () => rootRouteImport,
} as any)
const PriserRoute = PriserRouteImport.update({
  id: '/priser',
  path: '/priser',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdbogRoute = OrdbogRouteImport.update({
  id: '/ordbog',
  path: '/ordbog',
  getParentRoute: () => rootRouteImport,
} as any)
const OmRoute = OmRouteImport.update({
  id: '/om',
  path: '/om',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndsigterRoute = IndsigterRouteImport.update({
  id: '/indsigter',
  path: '/indsigter',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const DatakilderRoute = DatakilderRouteImport.update({
  id: '/datakilder',
  path: '/datakilder',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BrancherRoute = BrancherRouteImport.update({
  id: '/brancher',
  path: '/brancher',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDemoRoute = BookDemoRouteImport.update({
  id: '/book-demo',
  path: '/book-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRoute,
} as any)
const UseCasesSlugRoute = UseCasesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => UseCasesRoute,
} as any)
const ProblemerSlugRoute = ProblemerSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProblemerRoute,
} as any)
const PlatformSmartconnectRoute = PlatformSmartconnectRouteImport.update({
  id: '/smartconnect',
  path: '/smartconnect',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformImpactExchangeRoute = PlatformImpactExchangeRouteImport.update({
  id: '/impact-exchange',
  path: '/impact-exchange',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformEsgLedgerRoute = PlatformEsgLedgerRouteImport.update({
  id: '/esg-ledger',
  path: '/esg-ledger',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformDecisionsiqRoute = PlatformDecisionsiqRouteImport.update({
  id: '/decisionsiq',
  path: '/decisionsiq',
  getParentRoute: () => PlatformRoute,
} as any)
const OrdbogTermRoute = OrdbogTermRouteImport.update({
  id: '/$term',
  path: '/$term',
  getParentRoute: () => OrdbogRoute,
} as any)
const LoesningerNaturprojekterRoute =
  LoesningerNaturprojekterRouteImport.update({
    id: '/loesninger/naturprojekter',
    path: '/loesninger/naturprojekter',
    getParentRoute: () => rootRouteImport,
  } as any)
const LoesningerKommunerRoute = LoesningerKommunerRouteImport.update({
  id: '/loesninger/kommuner',
  path: '/loesninger/kommuner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoesningerIndustriRoute = LoesningerIndustriRouteImport.update({
  id: '/loesninger/industri',
  path: '/loesninger/industri',
  getParentRoute: () => rootRouteImport,
} as any)
const LoesningerEsgComplianceRoute = LoesningerEsgComplianceRouteImport.update({
  id: '/loesninger/esg-compliance',
  path: '/loesninger/esg-compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndsigterSlugRoute = IndsigterSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => IndsigterRoute,
} as any)
const EnPricingRoute = EnPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => EnRoute,
} as any)
const EnPlatformRoute = EnPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => EnRoute,
} as any)
const EnDashboardRoute = EnDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => EnRoute,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => EnRoute,
} as any)
const EnBookDemoRoute = EnBookDemoRouteImport.update({
  id: '/book-demo',
  path: '/book-demo',
  getParentRoute: () => EnRoute,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => EnRoute,
} as any)
const DataSlugRoute = DataSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DataRoute,
} as any)
const BrancherSlugRoute = BrancherSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BrancherRoute,
} as any)
const ApiAiEsgAnalyseRoute = ApiAiEsgAnalyseRouteImport.update({
  id: '/api/ai-esg-analyse',
  path: '/api/ai-esg-analyse',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPlatformSmartconnectRoute = EnPlatformSmartconnectRouteImport.update({
  id: '/smartconnect',
  path: '/smartconnect',
  getParentRoute: () => EnPlatformRoute,
} as any)
const EnPlatformImpactExchangeRoute =
  EnPlatformImpactExchangeRouteImport.update({
    id: '/impact-exchange',
    path: '/impact-exchange',
    getParentRoute: () => EnPlatformRoute,
  } as any)
const EnPlatformEsgLedgerRoute = EnPlatformEsgLedgerRouteImport.update({
  id: '/esg-ledger',
  path: '/esg-ledger',
  getParentRoute: () => EnPlatformRoute,
} as any)
const EnPlatformDecisionsiqRoute = EnPlatformDecisionsiqRouteImport.update({
  id: '/decisionsiq',
  path: '/decisionsiq',
  getParentRoute: () => EnPlatformRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book-demo': typeof BookDemoRoute
  '/brancher': typeof BrancherRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRouteWithChildren
  '/datakilder': typeof DatakilderRoute
  '/en': typeof EnRouteWithChildren
  '/indsigter': typeof IndsigterRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/om': typeof OmRoute
  '/ordbog': typeof OrdbogRouteWithChildren
  '/platform': typeof PlatformRouteWithChildren
  '/priser': typeof PriserRoute
  '/problemer': typeof ProblemerRouteWithChildren
  '/projekter': typeof ProjekterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/use-cases': typeof UseCasesRouteWithChildren
  '/api/ai-esg-analyse': typeof ApiAiEsgAnalyseRoute
  '/brancher/$slug': typeof BrancherSlugRoute
  '/data/$slug': typeof DataSlugRoute
  '/en/about': typeof EnAboutRoute
  '/en/book-demo': typeof EnBookDemoRoute
  '/en/contact': typeof EnContactRoute
  '/en/dashboard': typeof EnDashboardRoute
  '/en/platform': typeof EnPlatformRouteWithChildren
  '/en/pricing': typeof EnPricingRoute
  '/indsigter/$slug': typeof IndsigterSlugRoute
  '/loesninger/esg-compliance': typeof LoesningerEsgComplianceRoute
  '/loesninger/industri': typeof LoesningerIndustriRoute
  '/loesninger/kommuner': typeof LoesningerKommunerRoute
  '/loesninger/naturprojekter': typeof LoesningerNaturprojekterRoute
  '/ordbog/$term': typeof OrdbogTermRoute
  '/platform/decisionsiq': typeof PlatformDecisionsiqRoute
  '/platform/esg-ledger': typeof PlatformEsgLedgerRoute
  '/platform/impact-exchange': typeof PlatformImpactExchangeRoute
  '/platform/smartconnect': typeof PlatformSmartconnectRoute
  '/problemer/$slug': typeof ProblemerSlugRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/en/': typeof EnIndexRoute
  '/en/platform/decisionsiq': typeof EnPlatformDecisionsiqRoute
  '/en/platform/esg-ledger': typeof EnPlatformEsgLedgerRoute
  '/en/platform/impact-exchange': typeof EnPlatformImpactExchangeRoute
  '/en/platform/smartconnect': typeof EnPlatformSmartconnectRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book-demo': typeof BookDemoRoute
  '/brancher': typeof BrancherRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRouteWithChildren
  '/datakilder': typeof DatakilderRoute
  '/indsigter': typeof IndsigterRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/om': typeof OmRoute
  '/ordbog': typeof OrdbogRouteWithChildren
  '/platform': typeof PlatformRouteWithChildren
  '/priser': typeof PriserRoute
  '/problemer': typeof ProblemerRouteWithChildren
  '/projekter': typeof ProjekterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/use-cases': typeof UseCasesRouteWithChildren
  '/api/ai-esg-analyse': typeof ApiAiEsgAnalyseRoute
  '/brancher/$slug': typeof BrancherSlugRoute
  '/data/$slug': typeof DataSlugRoute
  '/en/about': typeof EnAboutRoute
  '/en/book-demo': typeof EnBookDemoRoute
  '/en/contact': typeof EnContactRoute
  '/en/dashboard': typeof EnDashboardRoute
  '/en/platform': typeof EnPlatformRouteWithChildren
  '/en/pricing': typeof EnPricingRoute
  '/indsigter/$slug': typeof IndsigterSlugRoute
  '/loesninger/esg-compliance': typeof LoesningerEsgComplianceRoute
  '/loesninger/industri': typeof LoesningerIndustriRoute
  '/loesninger/kommuner': typeof LoesningerKommunerRoute
  '/loesninger/naturprojekter': typeof LoesningerNaturprojekterRoute
  '/ordbog/$term': typeof OrdbogTermRoute
  '/platform/decisionsiq': typeof PlatformDecisionsiqRoute
  '/platform/esg-ledger': typeof PlatformEsgLedgerRoute
  '/platform/impact-exchange': typeof PlatformImpactExchangeRoute
  '/platform/smartconnect': typeof PlatformSmartconnectRoute
  '/problemer/$slug': typeof ProblemerSlugRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/en': typeof EnIndexRoute
  '/en/platform/decisionsiq': typeof EnPlatformDecisionsiqRoute
  '/en/platform/esg-ledger': typeof EnPlatformEsgLedgerRoute
  '/en/platform/impact-exchange': typeof EnPlatformImpactExchangeRoute
  '/en/platform/smartconnect': typeof EnPlatformSmartconnectRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book-demo': typeof BookDemoRoute
  '/brancher': typeof BrancherRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRouteWithChildren
  '/datakilder': typeof DatakilderRoute
  '/en': typeof EnRouteWithChildren
  '/indsigter': typeof IndsigterRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/om': typeof OmRoute
  '/ordbog': typeof OrdbogRouteWithChildren
  '/platform': typeof PlatformRouteWithChildren
  '/priser': typeof PriserRoute
  '/problemer': typeof ProblemerRouteWithChildren
  '/projekter': typeof ProjekterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/use-cases': typeof UseCasesRouteWithChildren
  '/api/ai-esg-analyse': typeof ApiAiEsgAnalyseRoute
  '/brancher/$slug': typeof BrancherSlugRoute
  '/data/$slug': typeof DataSlugRoute
  '/en/about': typeof EnAboutRoute
  '/en/book-demo': typeof EnBookDemoRoute
  '/en/contact': typeof EnContactRoute
  '/en/dashboard': typeof EnDashboardRoute
  '/en/platform': typeof EnPlatformRouteWithChildren
  '/en/pricing': typeof EnPricingRoute
  '/indsigter/$slug': typeof IndsigterSlugRoute
  '/loesninger/esg-compliance': typeof LoesningerEsgComplianceRoute
  '/loesninger/industri': typeof LoesningerIndustriRoute
  '/loesninger/kommuner': typeof LoesningerKommunerRoute
  '/loesninger/naturprojekter': typeof LoesningerNaturprojekterRoute
  '/ordbog/$term': typeof OrdbogTermRoute
  '/platform/decisionsiq': typeof PlatformDecisionsiqRoute
  '/platform/esg-ledger': typeof PlatformEsgLedgerRoute
  '/platform/impact-exchange': typeof PlatformImpactExchangeRoute
  '/platform/smartconnect': typeof PlatformSmartconnectRoute
  '/problemer/$slug': typeof ProblemerSlugRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/en/': typeof EnIndexRoute
  '/en/platform/decisionsiq': typeof EnPlatformDecisionsiqRoute
  '/en/platform/esg-ledger': typeof EnPlatformEsgLedgerRoute
  '/en/platform/impact-exchange': typeof EnPlatformImpactExchangeRoute
  '/en/platform/smartconnect': typeof EnPlatformSmartconnectRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book-demo'
    | '/brancher'
    | '/dashboard'
    | '/data'
    | '/datakilder'
    | '/en'
    | '/indsigter'
    | '/kontakt'
    | '/om'
    | '/ordbog'
    | '/platform'
    | '/priser'
    | '/problemer'
    | '/projekter'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/use-cases'
    | '/api/ai-esg-analyse'
    | '/brancher/$slug'
    | '/data/$slug'
    | '/en/about'
    | '/en/book-demo'
    | '/en/contact'
    | '/en/dashboard'
    | '/en/platform'
    | '/en/pricing'
    | '/indsigter/$slug'
    | '/loesninger/esg-compliance'
    | '/loesninger/industri'
    | '/loesninger/kommuner'
    | '/loesninger/naturprojekter'
    | '/ordbog/$term'
    | '/platform/decisionsiq'
    | '/platform/esg-ledger'
    | '/platform/impact-exchange'
    | '/platform/smartconnect'
    | '/problemer/$slug'
    | '/use-cases/$slug'
    | '/en/'
    | '/en/platform/decisionsiq'
    | '/en/platform/esg-ledger'
    | '/en/platform/impact-exchange'
    | '/en/platform/smartconnect'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book-demo'
    | '/brancher'
    | '/dashboard'
    | '/data'
    | '/datakilder'
    | '/indsigter'
    | '/kontakt'
    | '/om'
    | '/ordbog'
    | '/platform'
    | '/priser'
    | '/problemer'
    | '/projekter'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/use-cases'
    | '/api/ai-esg-analyse'
    | '/brancher/$slug'
    | '/data/$slug'
    | '/en/about'
    | '/en/book-demo'
    | '/en/contact'
    | '/en/dashboard'
    | '/en/platform'
    | '/en/pricing'
    | '/indsigter/$slug'
    | '/loesninger/esg-compliance'
    | '/loesninger/industri'
    | '/loesninger/kommuner'
    | '/loesninger/naturprojekter'
    | '/ordbog/$term'
    | '/platform/decisionsiq'
    | '/platform/esg-ledger'
    | '/platform/impact-exchange'
    | '/platform/smartconnect'
    | '/problemer/$slug'
    | '/use-cases/$slug'
    | '/en'
    | '/en/platform/decisionsiq'
    | '/en/platform/esg-ledger'
    | '/en/platform/impact-exchange'
    | '/en/platform/smartconnect'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/book-demo'
    | '/brancher'
    | '/dashboard'
    | '/data'
    | '/datakilder'
    | '/en'
    | '/indsigter'
    | '/kontakt'
    | '/om'
    | '/ordbog'
    | '/platform'
    | '/priser'
    | '/problemer'
    | '/projekter'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/use-cases'
    | '/api/ai-esg-analyse'
    | '/brancher/$slug'
    | '/data/$slug'
    | '/en/about'
    | '/en/book-demo'
    | '/en/contact'
    | '/en/dashboard'
    | '/en/platform'
    | '/en/pricing'
    | '/indsigter/$slug'
    | '/loesninger/esg-compliance'
    | '/loesninger/industri'
    | '/loesninger/kommuner'
    | '/loesninger/naturprojekter'
    | '/ordbog/$term'
    | '/platform/decisionsiq'
    | '/platform/esg-ledger'
    | '/platform/impact-exchange'
    | '/platform/smartconnect'
    | '/problemer/$slug'
    | '/use-cases/$slug'
    | '/en/'
    | '/en/platform/decisionsiq'
    | '/en/platform/esg-ledger'
    | '/en/platform/impact-exchange'
    | '/en/platform/smartconnect'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookDemoRoute: typeof BookDemoRoute
  BrancherRoute: typeof BrancherRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DataRoute: typeof DataRouteWithChildren
  DatakilderRoute: typeof DatakilderRoute
  EnRoute: typeof EnRouteWithChildren
  IndsigterRoute: typeof IndsigterRouteWithChildren
  KontaktRoute: typeof KontaktRoute
  OmRoute: typeof OmRoute
  OrdbogRoute: typeof OrdbogRouteWithChildren
  PlatformRoute: typeof PlatformRouteWithChildren
  PriserRoute: typeof PriserRoute
  ProblemerRoute: typeof ProblemerRouteWithChildren
  ProjekterRoute: typeof ProjekterRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UseCasesRoute: typeof UseCasesRouteWithChildren
  ApiAiEsgAnalyseRoute: typeof ApiAiEsgAnalyseRoute
  LoesningerEsgComplianceRoute: typeof LoesningerEsgComplianceRoute
  LoesningerIndustriRoute: typeof LoesningerIndustriRoute
  LoesningerKommunerRoute: typeof LoesningerKommunerRoute
  LoesningerNaturprojekterRoute: typeof LoesningerNaturprojekterRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekter': {
      id: '/projekter'
      path: '/projekter'
      fullPath: '/projekter'
      preLoaderRoute: typeof ProjekterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problemer': {
      id: '/problemer'
      path: '/problemer'
      fullPath: '/problemer'
      preLoaderRoute: typeof ProblemerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priser': {
      id: '/priser'
      path: '/priser'
      fullPath: '/priser'
      preLoaderRoute: typeof PriserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordbog': {
      id: '/ordbog'
      path: '/ordbog'
      fullPath: '/ordbog'
      preLoaderRoute: typeof OrdbogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om': {
      id: '/om'
      path: '/om'
      fullPath: '/om'
      preLoaderRoute: typeof OmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indsigter': {
      id: '/indsigter'
      path: '/indsigter'
      fullPath: '/indsigter'
      preLoaderRoute: typeof IndsigterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datakilder': {
      id: '/datakilder'
      path: '/datakilder'
      fullPath: '/datakilder'
      preLoaderRoute: typeof DatakilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brancher': {
      id: '/brancher'
      path: '/brancher'
      fullPath: '/brancher'
      preLoaderRoute: typeof BrancherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-demo': {
      id: '/book-demo'
      path: '/book-demo'
      fullPath: '/book-demo'
      preLoaderRoute: typeof BookDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/use-cases/$slug': {
      id: '/use-cases/$slug'
      path: '/$slug'
      fullPath: '/use-cases/$slug'
      preLoaderRoute: typeof UseCasesSlugRouteImport
      parentRoute: typeof UseCasesRoute
    }
    '/problemer/$slug': {
      id: '/problemer/$slug'
      path: '/$slug'
      fullPath: '/problemer/$slug'
      preLoaderRoute: typeof ProblemerSlugRouteImport
      parentRoute: typeof ProblemerRoute
    }
    '/platform/smartconnect': {
      id: '/platform/smartconnect'
      path: '/smartconnect'
      fullPath: '/platform/smartconnect'
      preLoaderRoute: typeof PlatformSmartconnectRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/impact-exchange': {
      id: '/platform/impact-exchange'
      path: '/impact-exchange'
      fullPath: '/platform/impact-exchange'
      preLoaderRoute: typeof PlatformImpactExchangeRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/esg-ledger': {
      id: '/platform/esg-ledger'
      path: '/esg-ledger'
      fullPath: '/platform/esg-ledger'
      preLoaderRoute: typeof PlatformEsgLedgerRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/decisionsiq': {
      id: '/platform/decisionsiq'
      path: '/decisionsiq'
      fullPath: '/platform/decisionsiq'
      preLoaderRoute: typeof PlatformDecisionsiqRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/ordbog/$term': {
      id: '/ordbog/$term'
      path: '/$term'
      fullPath: '/ordbog/$term'
      preLoaderRoute: typeof OrdbogTermRouteImport
      parentRoute: typeof OrdbogRoute
    }
    '/loesninger/naturprojekter': {
      id: '/loesninger/naturprojekter'
      path: '/loesninger/naturprojekter'
      fullPath: '/loesninger/naturprojekter'
      preLoaderRoute: typeof LoesningerNaturprojekterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loesninger/kommuner': {
      id: '/loesninger/kommuner'
      path: '/loesninger/kommuner'
      fullPath: '/loesninger/kommuner'
      preLoaderRoute: typeof LoesningerKommunerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loesninger/industri': {
      id: '/loesninger/industri'
      path: '/loesninger/industri'
      fullPath: '/loesninger/industri'
      preLoaderRoute: typeof LoesningerIndustriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loesninger/esg-compliance': {
      id: '/loesninger/esg-compliance'
      path: '/loesninger/esg-compliance'
      fullPath: '/loesninger/esg-compliance'
      preLoaderRoute: typeof LoesningerEsgComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indsigter/$slug': {
      id: '/indsigter/$slug'
      path: '/$slug'
      fullPath: '/indsigter/$slug'
      preLoaderRoute: typeof IndsigterSlugRouteImport
      parentRoute: typeof IndsigterRoute
    }
    '/en/pricing': {
      id: '/en/pricing'
      path: '/pricing'
      fullPath: '/en/pricing'
      preLoaderRoute: typeof EnPricingRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/platform': {
      id: '/en/platform'
      path: '/platform'
      fullPath: '/en/platform'
      preLoaderRoute: typeof EnPlatformRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/dashboard': {
      id: '/en/dashboard'
      path: '/dashboard'
      fullPath: '/en/dashboard'
      preLoaderRoute: typeof EnDashboardRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/book-demo': {
      id: '/en/book-demo'
      path: '/book-demo'
      fullPath: '/en/book-demo'
      preLoaderRoute: typeof EnBookDemoRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/about': {
      id: '/en/about'
      path: '/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof EnRoute
    }
    '/data/$slug': {
      id: '/data/$slug'
      path: '/$slug'
      fullPath: '/data/$slug'
      preLoaderRoute: typeof DataSlugRouteImport
      parentRoute: typeof DataRoute
    }
    '/brancher/$slug': {
      id: '/brancher/$slug'
      path: '/$slug'
      fullPath: '/brancher/$slug'
      preLoaderRoute: typeof BrancherSlugRouteImport
      parentRoute: typeof BrancherRoute
    }
    '/api/ai-esg-analyse': {
      id: '/api/ai-esg-analyse'
      path: '/api/ai-esg-analyse'
      fullPath: '/api/ai-esg-analyse'
      preLoaderRoute: typeof ApiAiEsgAnalyseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/platform/smartconnect': {
      id: '/en/platform/smartconnect'
      path: '/smartconnect'
      fullPath: '/en/platform/smartconnect'
      preLoaderRoute: typeof EnPlatformSmartconnectRouteImport
      parentRoute: typeof EnPlatformRoute
    }
    '/en/platform/impact-exchange': {
      id: '/en/platform/impact-exchange'
      path: '/impact-exchange'
      fullPath: '/en/platform/impact-exchange'
      preLoaderRoute: typeof EnPlatformImpactExchangeRouteImport
      parentRoute: typeof EnPlatformRoute
    }
    '/en/platform/esg-ledger': {
      id: '/en/platform/esg-ledger'
      path: '/esg-ledger'
      fullPath: '/en/platform/esg-ledger'
      preLoaderRoute: typeof EnPlatformEsgLedgerRouteImport
      parentRoute: typeof EnPlatformRoute
    }
    '/en/platform/decisionsiq': {
      id: '/en/platform/decisionsiq'
      path: '/decisionsiq'
      fullPath: '/en/platform/decisionsiq'
      preLoaderRoute: typeof EnPlatformDecisionsiqRouteImport
      parentRoute: typeof EnPlatformRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BrancherRouteChildren {
  BrancherSlugRoute: typeof BrancherSlugRoute
}

const BrancherRouteChildren: BrancherRouteChildren = {
  BrancherSlugRoute: BrancherSlugRoute,
}

const BrancherRouteWithChildren = BrancherRoute._addFileChildren(
  BrancherRouteChildren,
)

interface DataRouteChildren {
  DataSlugRoute: typeof DataSlugRoute
}

const DataRouteChildren: DataRouteChildren = {
  DataSlugRoute: DataSlugRoute,
}

const DataRouteWithChildren = DataRoute._addFileChildren(DataRouteChildren)

interface EnPlatformRouteChildren {
  EnPlatformDecisionsiqRoute: typeof EnPlatformDecisionsiqRoute
  EnPlatformEsgLedgerRoute: typeof EnPlatformEsgLedgerRoute
  EnPlatformImpactExchangeRoute: typeof EnPlatformImpactExchangeRoute
  EnPlatformSmartconnectRoute: typeof EnPlatformSmartconnectRoute
}

const EnPlatformRouteChildren: EnPlatformRouteChildren = {
  EnPlatformDecisionsiqRoute: EnPlatformDecisionsiqRoute,
  EnPlatformEsgLedgerRoute: EnPlatformEsgLedgerRoute,
  EnPlatformImpactExchangeRoute: EnPlatformImpactExchangeRoute,
  EnPlatformSmartconnectRoute: EnPlatformSmartconnectRoute,
}

const EnPlatformRouteWithChildren = EnPlatformRoute._addFileChildren(
  EnPlatformRouteChildren,
)

interface EnRouteChildren {
  EnAboutRoute: typeof EnAboutRoute
  EnBookDemoRoute: typeof EnBookDemoRoute
  EnContactRoute: typeof EnContactRoute
  EnDashboardRoute: typeof EnDashboardRoute
  EnPlatformRoute: typeof EnPlatformRouteWithChildren
  EnPricingRoute: typeof EnPricingRoute
  EnIndexRoute: typeof EnIndexRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnAboutRoute: EnAboutRoute,
  EnBookDemoRoute: EnBookDemoRoute,
  EnContactRoute: EnContactRoute,
  EnDashboardRoute: EnDashboardRoute,
  EnPlatformRoute: EnPlatformRouteWithChildren,
  EnPricingRoute: EnPricingRoute,
  EnIndexRoute: EnIndexRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

interface IndsigterRouteChildren {
  IndsigterSlugRoute: typeof IndsigterSlugRoute
}

const IndsigterRouteChildren: IndsigterRouteChildren = {
  IndsigterSlugRoute: IndsigterSlugRoute,
}

const IndsigterRouteWithChildren = IndsigterRoute._addFileChildren(
  IndsigterRouteChildren,
)

interface OrdbogRouteChildren {
  OrdbogTermRoute: typeof OrdbogTermRoute
}

const OrdbogRouteChildren: OrdbogRouteChildren = {
  OrdbogTermRoute: OrdbogTermRoute,
}

const OrdbogRouteWithChildren =
  OrdbogRoute._addFileChildren(OrdbogRouteChildren)

interface PlatformRouteChildren {
  PlatformDecisionsiqRoute: typeof PlatformDecisionsiqRoute
  PlatformEsgLedgerRoute: typeof PlatformEsgLedgerRoute
  PlatformImpactExchangeRoute: typeof PlatformImpactExchangeRoute
  PlatformSmartconnectRoute: typeof PlatformSmartconnectRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformDecisionsiqRoute: PlatformDecisionsiqRoute,
  PlatformEsgLedgerRoute: PlatformEsgLedgerRoute,
  PlatformImpactExchangeRoute: PlatformImpactExchangeRoute,
  PlatformSmartconnectRoute: PlatformSmartconnectRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

interface ProblemerRouteChildren {
  ProblemerSlugRoute: typeof ProblemerSlugRoute
}

const ProblemerRouteChildren: ProblemerRouteChildren = {
  ProblemerSlugRoute: ProblemerSlugRoute,
}

const ProblemerRouteWithChildren = ProblemerRoute._addFileChildren(
  ProblemerRouteChildren,
)

interface UseCasesRouteChildren {
  UseCasesSlugRoute: typeof UseCasesSlugRoute
}

const UseCasesRouteChildren: UseCasesRouteChildren = {
  UseCasesSlugRoute: UseCasesSlugRoute,
}

const UseCasesRouteWithChildren = UseCasesRoute._addFileChildren(
  UseCasesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookDemoRoute: BookDemoRoute,
  BrancherRoute: BrancherRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DataRoute: DataRouteWithChildren,
  DatakilderRoute: DatakilderRoute,
  EnRoute: EnRouteWithChildren,
  IndsigterRoute: IndsigterRouteWithChildren,
  KontaktRoute: KontaktRoute,
  OmRoute: OmRoute,
  OrdbogRoute: OrdbogRouteWithChildren,
  PlatformRoute: PlatformRouteWithChildren,
  PriserRoute: PriserRoute,
  ProblemerRoute: ProblemerRouteWithChildren,
  ProjekterRoute: ProjekterRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UseCasesRoute: UseCasesRouteWithChildren,
  ApiAiEsgAnalyseRoute: ApiAiEsgAnalyseRoute,
  LoesningerEsgComplianceRoute: LoesningerEsgComplianceRoute,
  LoesningerIndustriRoute: LoesningerIndustriRoute,
  LoesningerKommunerRoute: LoesningerKommunerRoute,
  LoesningerNaturprojekterRoute: LoesningerNaturprojekterRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
